/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import entidades.Bodega;
import datos.Dt_Bodega;
import entidades.WeCare;
import datos.Dt_WeCare;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Maria Regina
 */
public class FrmBodega extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Bodega
     */
    
    private Bodega b = new Bodega();
    private Dt_Bodega dtb = new Dt_Bodega();
    private ArrayList<Bodega> listaBodega = new ArrayList<Bodega>();
    
    private WeCare w = new WeCare();
    private Dt_WeCare dtwc = new Dt_WeCare();
    private ArrayList<WeCare> listaWeCare = new ArrayList<WeCare>();  
    
    
    DefaultTableModel myData = new DefaultTableModel();
    TableRowSorter trsfiltro;
    
    
    

    /**
     * Creates new form Bodega
     */
    public FrmBodega() {
        initComponents();
        llenarTablaBodega();
        llenarcombocare();
        limpiarCampos();    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_bodegaid = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_estado = new javax.swing.JTextField();
        bnuevo = new javax.swing.JButton();
        beditar = new javax.swing.JButton();
        bsuprimir = new javax.swing.JButton();
        bguardar = new javax.swing.JButton();
        jtf_descripcion = new javax.swing.JTextField();
        cbWeCare = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tablabod = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jtf_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bodega");
        setBackground(new java.awt.Color(230, 235, 240));

        jPanel1.setBackground(new java.awt.Color(27, 154, 170));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de Bodega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bodega_ID:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WeCare_ID:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado: ");

        jtf_bodegaid.setEditable(false);
        jtf_bodegaid.setBackground(new java.awt.Color(255, 255, 255));
        jtf_bodegaid.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_bodegaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_bodegaidActionPerformed(evt);
            }
        });
        jtf_bodegaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_bodegaidKeyTyped(evt);
            }
        });

        jtf_nombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombreKeyTyped(evt);
            }
        });

        jtf_estado.setEditable(false);
        jtf_estado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_estadoActionPerformed(evt);
            }
        });

        bnuevo.setBackground(new java.awt.Color(255, 102, 51));
        bnuevo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bnuevo.setForeground(new java.awt.Color(255, 255, 255));
        bnuevo.setText("Nuevo");
        bnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnuevoActionPerformed(evt);
            }
        });

        beditar.setBackground(new java.awt.Color(255, 102, 51));
        beditar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        beditar.setForeground(new java.awt.Color(255, 255, 255));
        beditar.setText("Editar");
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });

        bsuprimir.setBackground(new java.awt.Color(255, 102, 51));
        bsuprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bsuprimir.setForeground(new java.awt.Color(255, 255, 255));
        bsuprimir.setText("Suprimir");
        bsuprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuprimirActionPerformed(evt);
            }
        });

        bguardar.setBackground(new java.awt.Color(255, 102, 51));
        bguardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bguardar.setForeground(new java.awt.Color(255, 255, 255));
        bguardar.setText("Guardar");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });

        jtf_descripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_descripcionKeyTyped(evt);
            }
        });

        cbWeCare.setBackground(new java.awt.Color(255, 102, 51));
        cbWeCare.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbWeCare.setForeground(new java.awt.Color(255, 255, 255));
        cbWeCare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbWeCare, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_bodegaid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsuprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_bodegaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bnuevo)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbWeCare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addComponent(bguardar))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(beditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsuprimir)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jt_tablabod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "bodegaID", "weCareID", "nombreBodega", "descripcion", "estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_tablabod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tablabodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_tablabod);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel7.setText("Buscar: ");

        jtf_buscar.setText(" ");
        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed
        // TODO add your handling code here:
        //validamos que todos los campos sean ingresados por el usuario      
        if(cbWeCare.getSelectedIndex()==0|| jtf_descripcion.getText().equals("")|| jtf_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            b.setBodegaID(Integer.parseInt(jtf_bodegaid.getText()));
            w = (WeCare)this.cbWeCare.getItemAt(this.cbWeCare.getSelectedIndex());
            b.setWecareID(w.getWecareID());
            b.setDescripcion(jtf_descripcion.getText());
            b.setEstado(2);
            b.setNombreBodega(jtf_nombre.getText());
            
                       
            //validamos que el metodo actualizar devuelve un true
            if(dtb.editarBodega(b)){//**************************************************************************************
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }                  
    }//GEN-LAST:event_beditarActionPerformed

    private void bnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        
        
       
    }//GEN-LAST:event_bnuevoActionPerformed

        
    private void bsuprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuprimirActionPerformed
        // TODO add your handling code here:
        //validamos que todos los campos sean ingresados por el usuario      
        if(cbWeCare.getSelectedIndex()==0 || jtf_descripcion.getText().equals("")|| jtf_nombre.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            b.setBodegaID(Integer.parseInt(jtf_bodegaid.getText()));
            w = (WeCare)this.cbWeCare.getItemAt(this.cbWeCare.getSelectedIndex());
            b.setWecareID(w.getWecareID());
            b.setDescripcion(jtf_descripcion.getText());
            b.setEstado(3);
            b.setNombreBodega(jtf_nombre.getText());
            
            //validamos que el metodo delete devuelve un true
            if(dtb.deleteBodega(b)){

                JOptionPane.showMessageDialog (this, "El registro fue eliminado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }   
        
    }//GEN-LAST:event_bsuprimirActionPerformed
                                       
    
    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        // TODO add your handling code here:
        //validamos que todos los campos sean ingresados por el usuario      
        if(cbWeCare.getSelectedIndex()==0||jtf_descripcion.getText().equals("")|| jtf_nombre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            w = (WeCare)this.cbWeCare.getItemAt(this.cbWeCare.getSelectedIndex());
            b.setWecareID(w.getWecareID());
            b.setDescripcion(jtf_descripcion.getText());
            b.setEstado(1);
            b.setNombreBodega(jtf_nombre.getText());       
                                                                     
           
            //validamos que el id no exista en la tabla de la bd
            if(dtb.existeBodega (b)){//*************************************************************************************
                JOptionPane.showMessageDialog(this, "la bodega que intenta ingresar ya existe!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
                jtf_nombre.setText("");
                jtf_nombre.grabFocus();
                
            }
            else{
                //validamos que el metodo guardar devuelve un true
                if(dtb.guardarBodega(b)){//****************************************************************
                    JOptionPane.showMessageDialog (this, "El registro fue almacenado con éxito!", 
                      "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();
                }
                else{
                   JOptionPane.showMessageDialog(this, 
                      "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                      "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }       
    }//GEN-LAST:event_bguardarActionPerformed

    private void jtf_bodegaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_bodegaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_bodegaidActionPerformed

    private void jtf_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_estadoActionPerformed

    private void jtf_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombreKeyTyped
        // TODO add your handling code here:
        jtf_nombre.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_nombre.getText()).toUpperCase();
                jtf_nombre.setText(cadena);
                repaint();
            }
 
        });          
    }//GEN-LAST:event_jtf_nombreKeyTyped

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        // TODO add your handling code here:
        
        jtf_buscar.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_buscar.getText()).toUpperCase();
                jtf_buscar.setText(cadena);
                repaint();
                filtrarTabla();
            }
        });
        trsfiltro = new TableRowSorter(jt_tablabod.getModel());
        jt_tablabod.setRowSorter(trsfiltro);       
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jt_tablabodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tablabodMouseClicked
        // TODO add your handling code here:
               //obtenemos la fila seleccionada
        int fila = this.jt_tablabod.getSelectedRow();
        int idW = 0; // Guarda el idExpediente que se obtiene de la tabla
        int size = 0; // Guarda la cantidad de elementos que hay en el jcombobx de Locations
        int pos = 1; // Variable de control para recorrer las posiciones de los elementos en el jcombobox

        //asignamos los valores a los campos del formulario
        this.jtf_bodegaid.setText(this.jt_tablabod.getValueAt(fila, 0).toString());
        //this.cbWeCare.setSelectedIndex(Integer.parseInt(jt_tablabod.getValueAt(fila, 2).toString()));  
        this.jtf_nombre.setText(this.jt_tablabod.getValueAt(fila, 2).toString());
        this.jtf_descripcion.setText(this.jt_tablabod.getValueAt(fila, 3).toString());
        this.jtf_estado.setText(this.jt_tablabod.getValueAt(fila, 4).toString());
        
        // Obtenemos la fila seleccionada
             
        // Obtenemos el idConsulta del jtable
        idW = Integer.parseInt(this.jt_tablabod.getValueAt(fila, 1).toString());
        System.out.println("idLoc: "+idW);
  
        size = this.cbWeCare.getItemCount(); // Obtenemos la cantidad de elementos contenidos en el jcombobox
        System.out.println("size: "+size);
        do{
            
            w = (WeCare)this.cbWeCare.getItemAt(pos);
            if(w.getWecareID()==idW){
                // Selecciono el objeto del jcombobox
                this.cbWeCare.setSelectedIndex(pos);
                System.out.println("pos: "+pos);
                break;
            }
            pos++;
            
        }
        while(pos<=size);
        

    }//GEN-LAST:event_jt_tablabodMouseClicked

    private void jtf_bodegaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_bodegaidKeyTyped
      
    }//GEN-LAST:event_jtf_bodegaidKeyTyped

    private void jtf_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_descripcionKeyTyped
        // TODO add your handling code here:
        
        jtf_nombre.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_nombre.getText()).toUpperCase();
                jtf_nombre.setText(cadena);
                repaint();
            }
   
        });                  

    }//GEN-LAST:event_jtf_descripcionKeyTyped

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bodega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBodega().setVisible(true);
            }
        });
    } 
    
    
 //metodos
    

    

    
    private void actualizarTabla()
    {
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTablaBodega();
    }
    
    private void llenarTablaBodega()
    {
         //llenamos la lista
        listaBodega = dtb.listarBodega();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("bodegaID");
        listNombreColumnas.add("wecareID");
        listNombreColumnas.add("nombreBodega");
        listNombreColumnas.add("descripcion");
        listNombreColumnas.add("estado");
        //recorremos cada elemento del arraylist y creamos un objeto
        for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        
       //recorremos cada elemento de la lista y creamos el objeto
        for(Bodega bod: listaBodega){
            Object[] datosbod = new Object[]{bod.getBodegaID(), bod.getWecareID(), bod.getNombreBodega(), bod.getDescripcion(), bod.getEstado()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosbod);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        jt_tablabod.setModel(myData);
    }
    
    private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(jtf_buscar.getText(),2));
    }
    
    private void limpiarCampos()
    {
        this.jtf_bodegaid.setText("");
        this.cbWeCare.setSelectedIndex(0);   
        this.jtf_descripcion.setText("");
        this.jtf_estado.setText("");
        this.jtf_nombre.setText("");
       
    }
    
    private void llenarcombocare(){
        listaWeCare = dtwc.listarWeCare();
        
        for (WeCare z: listaWeCare){
            this.cbWeCare.addItem(z);
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beditar;
    private javax.swing.JButton bguardar;
    private javax.swing.JButton bnuevo;
    private javax.swing.JButton bsuprimir;
    private javax.swing.JComboBox<Object> cbWeCare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt_tablabod;
    private javax.swing.JTextField jtf_bodegaid;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_descripcion;
    private javax.swing.JTextField jtf_estado;
    private javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
