package presentacion;
import entidades.Producto;
import entidades.Tipoproducto;
import datos.Dt_Producto;
import datos.Dt_Tipoproducto;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Luswi Torres
 */
public class FrmProducto extends javax.swing.JFrame {
    
    // Atributos
    
    // Entidades
    private Producto product = new Producto();
    private Tipoproducto tprod = new Tipoproducto();
    
    // Datos
    private Dt_Producto dtp = new Dt_Producto();
    private Dt_Tipoproducto dttp = new Dt_Tipoproducto();
    
    // Listas de datos
    private ArrayList<Producto> listProduct = new ArrayList<Producto>();
    private ArrayList<Tipoproducto> listTprod = new ArrayList<Tipoproducto>();
    
    // Modelo de datos de la tabla
    DefaultTableModel myData = new DefaultTableModel();
    
    // Filtro de datos de la tabla
    TableRowSorter trsfiltro;
    
    // Constructor
    public FrmProducto() {
        initComponents();
        llenarComboTipoproducto();
        llenarTablaProducto();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_estado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        btn_mostrar_id = new javax.swing.JButton();
        jtf_nombre_producto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_precio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_ingreso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_vencimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtf_descripcion = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_suprimir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_producto = new javax.swing.JTable();
        jtf_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de los Productos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 154, 170));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jtf_id.setEditable(false);
        jtf_id.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado");

        jtf_estado.setEditable(false);
        jtf_estado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de Producto");

        jcb_tipo.setBackground(new java.awt.Color(255, 102, 51));
        jcb_tipo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jcb_tipo.setForeground(new java.awt.Color(255, 255, 255));
        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        btn_mostrar_id.setBackground(new java.awt.Color(255, 102, 51));
        btn_mostrar_id.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_mostrar_id.setForeground(new java.awt.Color(255, 255, 255));
        btn_mostrar_id.setText("...");
        btn_mostrar_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_idActionPerformed(evt);
            }
        });

        jtf_nombre_producto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_nombre_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombre_productoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio");

        jtf_precio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca");

        jtf_marca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Ingreso");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Vencimiento");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripcion");

        jtf_descripcion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        btn_nuevo.setBackground(new java.awt.Color(255, 102, 51));
        btn_nuevo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 102, 51));
        btn_editar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_suprimir.setBackground(new java.awt.Color(255, 102, 51));
        btn_suprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_suprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_suprimir.setText("Suprimir");
        btn_suprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suprimirActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(255, 102, 51));
        btn_guardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mostrar_id)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(52, 52, 52)
                                        .addComponent(jtf_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addGap(56, 56, 56)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_suprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_nuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btn_nuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_suprimir)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jtf_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtf_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_mostrar_id))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Buscar");

        jtbl_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "productoID", "tipoproductoID", "nombreProducto", "precio", "marca", "descripcion", "fechaIngreso", "fechaVencimiento", "estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_productoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbl_producto);

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_buscar))
                    .addComponent(jScrollPane2))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_idActionPerformed
        // TODO add your handling code here:
        if (jcb_tipo.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else {
            tprod = (Tipoproducto)this.jcb_tipo.getSelectedItem();
            JOptionPane.showMessageDialog(null, "ID:  "+tprod.getTipoproductoID());
        }
    }//GEN-LAST:event_btn_mostrar_idActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void jtbl_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_productoMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        //obtenemos la fila seleccionada del jtable
        int fila = this.jtbl_producto.getSelectedRow();
        int idTipo = 0; //guarda el idLocations que se obtiene de la tabla
        int size = 0; //guarda la cantidad de elementos que hay en el jcombobx de Locations
        int pos = 1; //variable de control para recorrer las posiciones de los elementos en el jcombobox
        
        //asignamos los valores a los campos del formulario
        this.jtf_id.setText(this.jtbl_producto.getValueAt(fila, 0).toString());
        this.jtf_nombre_producto.setText(this.jtbl_producto.getValueAt(fila, 2).toString());
        this.jtf_precio.setText(this.jtbl_producto.getValueAt(fila, 3).toString());
        this.jtf_marca.setText(this.jtbl_producto.getValueAt(fila, 4).toString());
        this.jtf_descripcion.setText(this.jtbl_producto.getValueAt(fila, 5).toString());
        this.jtf_ingreso.setText(this.jtbl_producto.getValueAt(fila, 6).toString());
        this.jtf_vencimiento.setText(this.jtbl_producto.getValueAt(fila, 7).toString());
        this.jtf_estado.setText(this.jtbl_producto.getValueAt(fila, 8).toString());
        
        //obtenemos el idLocations del jtable
        idTipo = Integer.parseInt(this.jtbl_producto.getValueAt(fila, 1).toString());
        size = this.jcb_tipo.getItemCount(); //obtenemos la cantidad de elementos contenidos en el jcombobox
        do{
            tprod = (Tipoproducto)this.jcb_tipo.getItemAt(pos);
            if(tprod.getTipoproductoID() == idTipo){
                //selecciono el objeto del jcombobox
                this.jcb_tipo.setSelectedIndex(pos);
                break;
            }
            pos++;
        }
        while(pos<=size);
    }//GEN-LAST:event_jtbl_productoMouseClicked

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        // TODO add your handling code here:
        jtf_buscar.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_buscar.getText()).toUpperCase();
                jtf_buscar.setText(cadena);
                repaint();
                filtrarTabla();
            }
        });
        trsfiltro = new TableRowSorter(jtbl_producto.getModel());
        jtbl_producto.setRowSorter(trsfiltro);
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jtf_nombre_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombre_productoKeyTyped
        // TODO add your handling code here:
        jtf_nombre_producto.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_nombre_producto.getText()).toUpperCase();
                jtf_nombre_producto.setText(cadena);
                repaint();
            }
        });
    }//GEN-LAST:event_jtf_nombre_productoKeyTyped

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        if (jcb_tipo.getSelectedIndex()==0 || jtf_nombre_producto.getText().equals("") || jtf_precio.getText().equals("") || jtf_marca.getText().equals("") || jtf_descripcion.getText().equals("") || jtf_ingreso.getText().equals("") || jtf_vencimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser rellenados!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //construimos nuestro objeto con los valores del formulario
            product.setProductoID(Integer.parseInt(jtf_id.getText()));
            tprod = (Tipoproducto)this.jcb_tipo.getItemAt(this.jcb_tipo.getSelectedIndex());
            product.setTipoproductoID(tprod.getTipoproductoID());
            product.setNombreProducto(jtf_nombre_producto.getText());
            product.setPrecio(Float.parseFloat(jtf_precio.getText()));
            product.setMarca(jtf_marca.getText());
            product.setDescripcion(jtf_descripcion.getText());
            product.setFechaIngreso(jtf_ingreso.getText());
            product.setFechaVencimiento(jtf_vencimiento.getText());
            product.setEstado(2);
            
            
            //validamos que el metodo guardar devuelve un true
            if(dtp.editarProd(product)){
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
                    
            }
            else {
                JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_suprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suprimirActionPerformed
        // TODO add your handling code here:
        if (jcb_tipo.getSelectedIndex()==0 || jtf_nombre_producto.getText().equals("") || jtf_precio.getText().equals("") || jtf_marca.getText().equals("") || jtf_descripcion.getText().equals("") || jtf_ingreso.getText().equals("") || jtf_vencimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser rellenados!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //construimos nuestro objeto con los valores del formulario
            product.setProductoID(Integer.parseInt(jtf_id.getText()));
            tprod = (Tipoproducto)this.jcb_tipo.getItemAt(this.jcb_tipo.getSelectedIndex());
            product.setTipoproductoID(tprod.getTipoproductoID());
            product.setNombreProducto(jtf_nombre_producto.getText());
            product.setPrecio(Float.parseFloat(jtf_precio.getText()));
            product.setMarca(jtf_marca.getText());
            product.setDescripcion(jtf_descripcion.getText());
            product.setFechaIngreso(jtf_ingreso.getText());
            product.setFechaVencimiento(jtf_vencimiento.getText());
            product.setEstado(3);
            
            
            //validamos que el metodo guardar devuelve un true
            if(dtp.deleteProd(product)){
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
                    
            }
            else {
                JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btn_suprimirActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (jcb_tipo.getSelectedIndex()==0 || jtf_nombre_producto.getText().equals("") || jtf_precio.getText().equals("") || jtf_marca.getText().equals("") || jtf_descripcion.getText().equals("") || jtf_ingreso.getText().equals("") || jtf_vencimiento.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben ser rellenados!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else {
            //construimos nuestro objeto con los valores del formulario
            //product.setProductoID(Integer.parseInt(jtf_id.getText()));
            tprod = (Tipoproducto)this.jcb_tipo.getItemAt(this.jcb_tipo.getSelectedIndex());
            product.setTipoproductoID(tprod.getTipoproductoID());
            product.setNombreProducto(jtf_nombre_producto.getText());
            product.setPrecio(Float.parseFloat(jtf_precio.getText()));
            product.setMarca(jtf_marca.getText());
            product.setDescripcion(jtf_descripcion.getText());
            product.setFechaIngreso(jtf_ingreso.getText());
            product.setFechaVencimiento(jtf_vencimiento.getText());
            product.setEstado(1);
            
            //validamos que el id no exista en la tabla de la bd
            if(dtp.existeProd(product)){
                JOptionPane.showMessageDialog(this, "El ID del usuario ya existe!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
                jtf_id.setText("");
                jtf_id.grabFocus(); 
            }
            else {
                //validamos que el metodo guardar devuelve un true
                if(dtp.guardarProd(product)){
                    JOptionPane.showMessageDialog (this, "El registro fue almacenado con éxito!", 
                      "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();
                    
                }
                else {
                   JOptionPane.showMessageDialog(this, 
                      "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                      "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }
    
    
    private void llenarComboTipoproducto(){
        //llenamos la lista
        listTprod = dttp.listarTipoproducto();
        
        for(Tipoproducto typeproduct: listTprod){
            //llenar el combobox con los objetos de la lista
            this.jcb_tipo.addItem(typeproduct);
            //this.jcb_locations.addItem(l.toString());
        }
    }
    
    
    private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTablaProducto();
    }
    
    
    private void llenarTablaProducto()
    {
         //llenamos la lista
        listProduct = dtp.listarProd();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("productoID");
        listNombreColumnas.add("tipoproductoID");
        listNombreColumnas.add("nombreProducto");
        listNombreColumnas.add("precio");
        listNombreColumnas.add("marca");
        listNombreColumnas.add("descripcion");
        listNombreColumnas.add("fechaIngreso");
        listNombreColumnas.add("fechaVencimiento");
        listNombreColumnas.add("estado");
        //recorremos cada elemento del arraylist y creamos un objeto
        for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        
       //recorremos cada elemento de la lista y creamos el objeto
        for(Producto product: listProduct){
            Object[] datosProducto = new Object[]{product.getProductoID(), product.getTipoproductoID(), product.getNombreProducto(), product.getPrecio(), product.getMarca(), product.getDescripcion(), product.getFechaIngreso(), product.getFechaVencimiento(), product.getEstado()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosProducto);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        jtbl_producto.setModel(myData);
    }
    
    
    private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(jtf_buscar.getText(),2));
    }
    
    
    private void limpiarCampos()
    {
        this.jtf_id.setText("");
        this.jtf_estado.setText("");
        this.jcb_tipo.setSelectedIndex(0);
        this.jtf_nombre_producto.setText("");
        this.jtf_precio.setText("");
        this.jtf_marca.setText("");
        this.jtf_descripcion.setText("");
        this.jtf_ingreso.setText("");
        this.jtf_vencimiento.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_mostrar_id;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_suprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Object> jcb_tipo;
    private javax.swing.JTable jtbl_producto;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_descripcion;
    private javax.swing.JTextField jtf_estado;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_ingreso;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_nombre_producto;
    private javax.swing.JTextField jtf_precio;
    private javax.swing.JTextField jtf_vencimiento;
    // End of variables declaration//GEN-END:variables
}
