package presentacion;
import entidades.Rol;
import entidades.Usuario;
import datos.Dt_Rol;
import datos.Dt_Usuario;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Luswi Torres
 */
public class Login extends javax.swing.JFrame {
    
    // Atributos
    
    // Entidades
    public static Rol rol = new Rol();
    public static Usuario user = new Usuario();
    
    // Datos
    Dt_Rol dtr = new Dt_Rol();
    Dt_Usuario dtu = new Dt_Usuario();
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpf_pwd = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jl_registro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 5, true));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("USUARIO");

        jtf_user.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtf_user.setForeground(new java.awt.Color(204, 204, 204));
        jtf_user.setText("Ingrese su nombre de usuario");
        jtf_user.setBorder(null);
        jtf_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtf_userMousePressed(evt);
            }
        });
        jtf_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_userKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA");

        jpf_pwd.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jpf_pwd.setForeground(new java.awt.Color(204, 204, 204));
        jpf_pwd.setText("************");
        jpf_pwd.setBorder(null);
        jpf_pwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpf_pwdMousePressed(evt);
            }
        });

        btn_entrar.setBackground(new java.awt.Color(0, 153, 153));
        btn_entrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("ENTRAR");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Logo WeCare 250x250.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));

        jLabel5.setText("© 2022 WeCare Todos los derechos resevados. ");

        jl_registro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jl_registro.setText("Nuevo en WeCare? Crea una cuenta.");
        jl_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_registroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_registroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btn_entrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jpf_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_user, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(178, 178, 178)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jpf_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_userMousePressed
        // TODO add your handling code here:
        if (jtf_user.getText().equals("Ingrese su nombre de usuario")) {
            jtf_user.setText("");
            jtf_user.setForeground(Color.black);
        }
        
        if (String.valueOf(jpf_pwd.getPassword()).isEmpty()) {
            jpf_pwd.setText("************");
            jpf_pwd.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtf_userMousePressed

    private void jpf_pwdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpf_pwdMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jpf_pwd.getPassword()).equals("************")) {
            jpf_pwd.setText("");
            jpf_pwd.setForeground(Color.black);
        }
        
        if (jtf_user.getText().isEmpty()) {
            jtf_user.setText("Ingrese su nombre de usuario");
            jtf_user.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jpf_pwdMousePressed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        String usuario = "";
        String password = "";
        
        usuario = jtf_user.getText();
        password = String.valueOf(jpf_pwd.getPassword());
        
        if(dtu.validarUsuario(usuario, password)){
            user = dtu.getUsuario(usuario);
            rol = dtr.getRolByID(user.getRolID());
            Principal frmP = new Principal();
            frmP.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, 
            "Sus datos de acceso no son válidos. Ingrese nuevamente sus datos y vuelva a intetarlo!", 
            "ERROR", JOptionPane.ERROR_MESSAGE); 
            this.limpiarCampos();
            this.jtf_user.grabFocus();
        }
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void jl_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMouseEntered
        // TODO add your handling code here:
        jl_registro.setForeground(Color.blue);
    }//GEN-LAST:event_jl_registroMouseEntered

    private void jl_registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMouseExited
        jl_registro.setForeground(Color.black);
    }//GEN-LAST:event_jl_registroMouseExited

    private void jl_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMouseClicked
        // TODO add your handling code here:
        FrmRegistro registro = new FrmRegistro();
        registro.setVisible(true);
    }//GEN-LAST:event_jl_registroMouseClicked

    private void jtf_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_userKeyTyped
        jtf_user.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtf_user.getText()).toUpperCase();
                jtf_user.setText(cadena);
                repaint();
            }
        });
    }//GEN-LAST:event_jtf_userKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    private void limpiarCampos(){
        jtf_user.setText("Ingrese su nombre de usuario");
        jtf_user.setForeground(Color.gray);
        jpf_pwd.setText("************");
        jpf_pwd.setForeground(Color.gray);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jl_registro;
    private javax.swing.JPasswordField jpf_pwd;
    private javax.swing.JTextField jtf_user;
    // End of variables declaration//GEN-END:variables
}
